name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: write
    pages: write
    id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: update version in repo
        env:
          tag: ${{ github.ref_name }}
        run: |
          tmp=$(mktemp)
          jq --arg version $tag '.versions |= [$version] + .' versions.json > "$tmp" && mv "$tmp" versions.json
          git config --global user.name 'Alan Bits'
          git config --global user.email 'alan@lnbits.com'
          git commit -am "[CHORE] update version to $tag"
          git push
          git push --delete origin $tag
          git tag -fa $tag -m "update via workflow"
          git push --tags

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: build sketch with arduino cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          sh install.sh
          sh build.sh tdisplay

      - name: Create github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" --generate-notes ./build/snsd.ino.bootloader.bin \
            ./build/snsd.ino.bin ./build/snsd.ino.partitions.bin
